/*

--FACT_DADES_ACADEMIQUES: 
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'STAGE_DADES_ACADEMIQUES_COCO' As tabla        from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO UNION ALL  
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'STAGE_DADES_ACADEMIQUES_DIMAX' As tabla      from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX UNION ALL  
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'POST_DADES_ACADEMIQUES_RA' As tabla             from  DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA UNION ALL
-- EVENTS  
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'STAGE_LIVE_EVENTS_FLATENED_RA' As tabla         from DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA   UNION ALL  
-- FACTS  
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'FACT_RECURSOS_APRENENTATGE_EVENTS' As tabla      from DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS  UNION ALL  
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'FACT_DADES_RECURSOS_APRENENTATGE_AGG' As tabla  from DB_UOC_PROD.DDP_DOCENCIA.FACT_DADES_RECURSOS_APRENENTATGE_AGG UNION ALL 


-- DIM_RECURSOS_APRENENTATGE: 
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'STAGE_RECURSOS_APRENENTATGE_DIMAX' As tabla        from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX UNION ALL  
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS' As tabla      from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS UNION ALL  
select count(*), count(distinct *), count(DISTINCT CODI_RECURS), COUNT(DISTINCT DIM_ASSIGNATURA_KEY), 'DIM_RECURSOS_APRENENTATGE' As tabla             from  DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE 

*/


---~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--VERIFICACIONES
--FACT_DADES_ACADEMIQUES: 
select 
    count(*) 
    , count(distinct CODI_RECURS, DIM_ASSIGNATURA_KEY, dim_semestre_key ) as mix_distinc 
    , count(DISTINCT CODI_RECURS) as recurs
    , COUNT(DISTINCT DIM_ASSIGNATURA_KEY) as asignatura
    , 'STAGE_DADES_ACADEMIQUES_COCO' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO  

UNION ALL

select 
    count(*) 
    , count(distinct CODI_RECURS, DIM_ASSIGNATURA_KEY, dim_semestre_key ) as mix_distinc 
    , count(DISTINCT CODI_RECURS) as recurs
    , COUNT(DISTINCT DIM_ASSIGNATURA_KEY) as asignatura
    , 'STAGE_DADES_ACADEMIQUES_DIMAX' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX  

UNION ALL

select 
    count(*) 
    , count(distinct CODI_RECURS, DIM_ASSIGNATURA_KEY, dim_semestre_key ) as mix_distinc 
    , count(DISTINCT CODI_RECURS) as recurs
    , COUNT(DISTINCT DIM_ASSIGNATURA_KEY) as asignatura
    , 'POST_DADES_ACADEMIQUES_RA' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA  

-- EVENTS  
UNION ALL 
select 
    count(*) 
    , count(distinct CODI_RECURS, DIM_ASSIGNATURA_KEY, dim_semestre_key ) as mix_distinc 
    , count(DISTINCT CODI_RECURS) as recurs
    , COUNT(DISTINCT DIM_ASSIGNATURA_KEY) as asignatura
    , 'STAGE_LIVE_EVENTS_FLATENED_RA' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA  


-- FACTS  : convertimos codi_recurs a dim_recursos_aprenentatge_key
UNION ALL 
select 
    count(*) 
    , count(distinct dim_recursos_aprenentatge_key, DIM_ASSIGNATURA_KEY, dim_semestre_key ) as mix_distinc 
    , count(DISTINCT dim_recursos_aprenentatge_key) as recurs
    , COUNT(DISTINCT DIM_ASSIGNATURA_KEY) as asignatura
    , 'FACT_RECURSOS_APRENENTATGE_EVENTS' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS


UNION ALL 
select 
    count(*) 
    , count(distinct dim_recursos_aprenentatge_key, DIM_ASSIGNATURA_KEY, dim_semestre_key ) as mix_distinc 
    , count(DISTINCT dim_recursos_aprenentatge_key) as recurs
    , COUNT(DISTINCT DIM_ASSIGNATURA_KEY) as asignatura
    , 'FACT_DADES_RECURSOS_APRENENTATGE_AGG' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS_AGG





-- DIM_RECURSOS_APRENENTATGE:
UNION ALL 
select 
    count(*) 
    , 0 as mix_distinc 
    , count(DISTINCT CODI_RECURS) as recurs
    , 0 as asignatura
    , 'STAGE_RECURSOS_APRENENTATGE_DIMAX' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX

UNION ALL 
select 
    count(*) 
    , 0 as mix_distinc 
    , count(DISTINCT CODI_RECURS) as recurs
    , 0 as asignatura
    , 'STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS

UNION ALL 
select 
    count(*) 
    , 0 as mix_distinc 
    , count(DISTINCT CODI_RECURS) as recurs
    , 0 as asignatura
    , 'DIM_RECURSOS_APRENENTATGE' As tabla        
from  DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE


/***

MIX_DISTINC: combinacion de asignatura y codi_recurs 

COUNT(*)	MIX_DISTINC	RECURS	ASIGNATURA	TABLA
1713249	    1713249	    52209	12197	STAGE_DADES_ACADEMIQUES_COCO
3390907	    3390907	    70357	14161	STAGE_DADES_ACADEMIQUES_DIMAX
5104156	    5104156	    116915	15797	POST_DADES_ACADEMIQUES_RA
91341	    11897	    9161	2085	STAGE_LIVE_EVENTS_FLATENED_RA
5174058	    5104156	    122566	15797	FACT_RECURSOS_APRENENTATGE_EVENTS
5104156	    5104156	    122566	15797	FACT_DADES_RECURSOS_APRENENTATGE_AGG

102166	    0	        102166	0	    STAGE_RECURSOS_APRENENTATGE_DIMAX
116900	    0	        116893	0	    STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS
219060	    0	        208930	0	    DIM_RECURSOS_APRENENTATGE

*/





---~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--- values all tables  
---~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- ARCHIVO: MODELS\DIM\DIM_RECURSOS_APRENENTATGE_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX UNION ALL


-- ARCHIVO: MODELS\FACT\FACT_RECURSOS_APRENENTATGE_EVENTS_AGG_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS_AGG' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS_AGG UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS UNION ALL


-- ARCHIVO: MODELS\FACT\FACT_RECURSOS_APRENENTATGE_EVENTS_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA  UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA' as table_name , count(*),  from DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA UNION ALL
SELECT 'DB_UOC_PROD.DD_OD.DIM_ASSIGNATURA' as table_name , count(*),  from DB_UOC_PROD.DD_OD.DIM_ASSIGNATURA UNION ALL
SELECT 'DB_UOC_PROD.DD_OD.DIM_SEMESTRE' as table_name , count(*),  from DB_UOC_PROD.DD_OD.DIM_SEMESTRE UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE' as table_name , count(*),  from DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE UNION ALL
SELECT 'DB_UOC_PROD.DD_OD.DIM_PERSONA' as table_name , count(*),  from DB_UOC_PROD.DD_OD.DIM_PERSONA UNION ALL


-- ARCHIVO: MODELS\POST\POST_DADES_ACADEMIQUES_RA_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.GAT_PERSONAS_ASIGNATURAS' as table_name , count(*) from DB_UOC_PROD.STG_DADESRA.GAT_PERSONAS_ASIGNATURAS UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX UNION ALL
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_ASIG_SEMESTRES' as table_name , count(*),  from DB_UOC_PROD.STG_DOCENCIA.GAT_ASIG_SEMESTRES UNION ALL


-- ARCHIVO: MODELS\STAGE\LOOKUP_IDIOMAS.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.LK_IDIOMA_2' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.LK_IDIOMA_2 UNION ALL


-- ARCHIVO: MODELS\STAGE\STAGE_DADES_ACADEMIQUES_COCO_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO UNION ALL
SELECT 'DB_UOC_PROD.DD_OD.DIM_SEMESTRE' as table_name , count(*) from DB_UOC_PROD.DD_OD.DIM_SEMESTRE UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_ELEMENT_FORMACIO' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.AUTORS_ELEMENT_FORMACIO UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_PRODUCTES_VERSIONS' as table_name , count(*) from DB_UOC_PROD.STG_DADESRA.AUTORS_PRODUCTES_VERSIONS UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_VERSIO' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.AUTORS_VERSIO UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_ELEMENT_FORMACIO' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.AUTORS_ELEMENT_FORMACIO UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_PERIODE' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.AUTORS_PERIODE UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE' as table_name , count(*),  from DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE UNION ALL
 


-- ARCHIVO: MODELS\STAGE\STAGE_DADES_ACADEMIQUES_DIMAX_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.DIMAX_RESOFITE_PATH' as table_name , count(*) from DB_UOC_PROD.STG_DADESRA.DIMAX_RESOFITE_PATH UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.DIMAX_ITEM_DIMAX' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.DIMAX_ITEM_DIMAX UNION ALL
 

-- ARCHIVO: MODELS\STAGE\STAGE_LIVE_EVENTS_FLATENED_RA_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.LIVE_EVENTS_CALIPER_DUMMY' as table_name , count(*) from DB_UOC_PROD.STG_DADESRA.LIVE_EVENTS_CALIPER_DUMMY UNION ALL
 

-- ARCHIVO: MODELS\STAGE\STAGE_RECURSOS_APRENENTATGE_COCO_CLEAN_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_CLEAN_PROCEDURE' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_CLEAN_PROCEDURE UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS UNION ALL



-- ARCHIVO: MODELS\STAGE\STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_PRODUCTE' as table_name , count(*) from DB_UOC_PROD.STG_DADESRA.AUTORS_PRODUCTE UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_SUPORT_PRODUCTE_I18N' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.AUTORS_SUPORT_PRODUCTE_I18N UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_TIPUS_TRAMESA_I18N' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.AUTORS_TIPUS_TRAMESA_I18N UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_IDIOMA_PRODUCTE_I18N' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.AUTORS_IDIOMA_PRODUCTE_I18N UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.AUTORS_MODUL' as table_name , count(*) from DB_UOC_PROD.STG_DADESRA.AUTORS_MODUL UNION ALL
 


-- ARCHIVO: MODELS\STAGE\STAGE_RECURSOS_APRENENTATGE_DIMAX_PROCEDURE.SQL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX' as table_name , count(*) from DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.DIMAX_V_RECURS' as table_name , count(*) from DB_UOC_PROD.STG_DADESRA.DIMAX_V_RECURS UNION ALL
SELECT 'DB_UOC_PROD.STG_DADESRA.DIMAX_RECURS_INFO_EXTRA' as table_name , count(*),  from DB_UOC_PROD.STG_DADESRA.DIMAX_RECURS_INFO_EXTRA UNION ALL
SELECT 'DB_UOC_PROD.DDP_DOCENCIA.LK_IDIOMA_2' as table_name , count(*),  from DB_UOC_PROD.DDP_DOCENCIA.LK_IDIOMA_2  



/*

 

COUNT(*)	TABLE_NAME
219067			DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE
116893			DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS
102166			DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX

5107627			DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS_AGG
16624076		DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS

16624076		DB_UOC_PROD.DDP_DOCENCIA.FACT_RECURSOS_APRENENTATGE_EVENTS
13573588		DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA
5104156			DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA
13573588		DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA
18091			DB_UOC_PROD.DD_OD.DIM_ASSIGNATURA
84			    DB_UOC_PROD.DD_OD.DIM_SEMESTRE
219067			DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE
1244767			DB_UOC_PROD.DD_OD.DIM_PERSONA

5104156			DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES_RA
312270			DB_UOC_PROD.STG_DADESRA.GAT_PERSONAS_ASIGNATURAS  -- complementaria --> info profesor 
1713249			DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO
3390907			DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX
16455			DB_UOC_PROD.STG_DOCENCIA.GAT_ASIG_SEMESTRES
20			    DB_UOC_PROD.DDP_DOCENCIA.LK_IDIOMA_2

1713249			DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO
84			    DB_UOC_PROD.DD_OD.DIM_SEMESTRE
16969			DB_UOC_PROD.STG_DADESRA.AUTORS_ELEMENT_FORMACIO
248597			DB_UOC_PROD.STG_DADESRA.AUTORS_PRODUCTES_VERSIONS
45583			DB_UOC_PROD.STG_DADESRA.AUTORS_VERSIO
16969			DB_UOC_PROD.STG_DADESRA.AUTORS_ELEMENT_FORMACIO
680			    DB_UOC_PROD.STG_DADESRA.AUTORS_PERIODE
219067			DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE

3390907			DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX
18058834		DB_UOC_PROD.STG_DADESRA.DIMAX_RESOFITE_PATH
1755802			DB_UOC_PROD.STG_DADESRA.DIMAX_ITEM_DIMAX

13573588		DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_RA
21407243		DB_UOC_PROD.STG_DADESRA.LIVE_EVENTS_CALIPER_DUMMY

0			    DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_CLEAN_PROCEDURE
116893			DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS

116893			DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_COCO_PRODUCT_MODULS
56052			DB_UOC_PROD.STG_DADESRA.AUTORS_PRODUCTE
93			    DB_UOC_PROD.STG_DADESRA.AUTORS_SUPORT_PRODUCTE_I18N
4			    DB_UOC_PROD.STG_DADESRA.AUTORS_TIPUS_TRAMESA_I18N
13			    DB_UOC_PROD.STG_DADESRA.AUTORS_IDIOMA_PRODUCTE_I18N
60848			DB_UOC_PROD.STG_DADESRA.AUTORS_MODUL

102166			DB_UOC_PROD.DDP_DOCENCIA.STAGE_RECURSOS_APRENENTATGE_DIMAX
102166			DB_UOC_PROD.STG_DADESRA.DIMAX_V_RECURS
11239			DB_UOC_PROD.STG_DADESRA.DIMAX_RECURS_INFO_EXTRA

20			    DB_UOC_PROD.DDP_DOCENCIA.LK_IDIOMA_2





*/