
-- 2024/12/04
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- FACT_DADES_ACADEMIQUES_EVENTS: 
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT 

    ID_ASSIGNATURA
    , ID_SEMESTRE
    , ID_CODI_RECURS
    , ID_PERSONA
    , DIM_PERSONA_KEY
    , DIM_ASSIGNATURA_KEY
    , DIM_SEMESTRE_KEY
    , DIM_RECURSOS_APRENENTATGE_KEY
    , SOURCE_DADES_ACADEMIQUES
    , CODI_RECURS
    , EVENT_CODI_RECURS
    , EVENT_TIME
    , EVENT_DATE
    , ACTION
    , ACTOR_NAME
    , ACTOR_TYPE
    , USERLOGIN
    , USER_SIS_ID
    , GROUP_NAME
    , CANVASCOURSEID
    , SISCOURSEID
    , ROL
    , MEMBERSHIP_STATUS
    , OBJECT_NAME
    , OBJECT_ID
    , OBJECT_MEDIATYPE
    , OBJECT_TYPE
    , FORMAT
    , SOURCE
    , URL

from DB_UOC_PROD.DDP_DOCENCIA.FACT_DADES_ACADEMIQUES_EVENTS ; 

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- DIM_RECURSOS_APRENENTATGE: 
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SELECT
    ID_CODI_RECURS
    , DIM_RECURSOS_APRENENTATGE_KEY
    , CODI_RECURS
    , TITOL_RECURS
    , ORIGEN_RECURS
    , TIPUS_RECURS
    , SOURCE_RECURS
    , LLICENCIA_LPC
    , LLICENCIA_LGC
    , LLICENCIA_ALTRES
    , LLICENCIA_BIBLIOTECA
    , BAIXA
    , DESCRIPCIO_IDIOMA_RECURS
    , FORMAT_RECURS
    , DATA_INICI_RECURS
    , DATA_CADUCITAT_RECURS
    , CERCABLE_RECURS
    , INDICADOR_PUBLIC_RECURS
    , PUBLICAT_A_RECURS
    , ISBN_ISSN_RECURS
    , PAGINA_INICI_RECURS
    , PAGINA_FINAL_RECURS
    , BASE_DADES_RECURS
    , ELLIBRE_RECURS
    , URL_CAT_RECURS
    , URL_CAS_RECURS
    , URL_ANG_RECURS
    , TIPUS_GESTIO_RECURS
    , DESPESA_VARIABLE_RECURS
    , UPDATE_DATE
    , CREATION_DATE
    , PRODUCTE_CREACIO_ID
    , DESCRIPCIO_TRAMESA_RECURS
    , NUM_CONTRACTE
    , OBSERVACIONS
    , MODUL_ORIGEN_ID
    , VERSIO_CREACIO_ID
    , OBRA_ID
    , CODI_MIGRACIO
    , URL_RECURS_PROPI

From DB_UOC_PROD.DDP_DOCENCIA.DIM_RECURSOS_APRENENTATGE;















