--DADES_ACADEMIQUES: 
select count(*), 'STAGE_DADES_ACADEMIQUES_COCO' As tabla from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO union all  
select count(*), 'STAGE_DADES_ACADEMIQUES_DIMAX' As tabla from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX union all  
select count(*), 'POST_DADES_ACADEMIQUES' As tabla from  DB_UOC_PROD.DDP_DOCENCIA.POST_DADES_ACADEMIQUES union all  


-- EVENTS
select count(*), 'STAGE_LIVE_EVENTS_FLATENED' As tabla from DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED   union all  
 
-- FACTS
select count(*), 'FACT_DADES_ACADEMIQUES_EVENTS' As tabla from DB_UOC_PROD.DDP_DOCENCIA.FACT_DADES_ACADEMIQUES_EVENTS  union all  
select count(*), 'FACT_DADES_ACADEMIQUES_EVENTS_AGG' As tabla from DB_UOC_PROD.DDP_DOCENCIA.FACT_DADES_ACADEMIQUES_EVENTS_AGG   