select count(*), 'STAGE_DADES_ACADEMIQUES_COCO' As tabla from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_COCO union all  
select count(*), 'STAGE_DADES_ACADEMIQUES_DIMAX' As tabla from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_DADES_ACADEMIQUES_DIMAX union all  
select count(*), 'STAGE_POST_DADES_ACADEMIQUES' As tabla from  DB_UOC_PROD.DDP_DOCENCIA.STAGE_POST_DADES_ACADEMIQUES union all  

select count(*), 'STAGE_LIVE_EVENTS_FLATENED' As tabla from DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED   union all  
select count(*), 'STAGE_LIVE_EVENTS_FLATENED_TRANSFORMED' As tabla from DB_UOC_PROD.DDP_DOCENCIA.STAGE_LIVE_EVENTS_FLATENED_TRANSFORMED  union all  



select count(*), 'STAGE_POST_DADES_ACADEMIQUES_EVENTS_ALL' As tabla from DB_UOC_PROD.DDP_DOCENCIA.STAGE_POST_DADES_ACADEMIQUES_EVENTS_ALL  union all  
select count(*), 'STAGE_POST_DADES_ACADEMIQUES_EVENTS_SIMPLIFIED' As tabla from DB_UOC_PROD.DDP_DOCENCIA.STAGE_POST_DADES_ACADEMIQUES_EVENTS_SIMPLIFIED   