-- EXTRACT VALUES FROM TABLE: 
SELECT     

    table_catalog || '.'||  table_schema || '.' ||  table_name AS TABLE_FULL_PATH
    , 'https://app.snowflake.com/walwzwz/uocbi/#/data/databases/' ||  table_catalog ||  '/schemas/' ||  table_schema ||  '/table/' ||  table_name   AS TABLE_LINK
    , *

FROM information_schema.tables
WHERE 1=1 
ORDER BY table_catalog, table_schema, table_name;


--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-----######################################## CREATE TABLE #########################################################
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PERSONA') AS ceation  union all
SELECT GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PERSONA') AS ceation  


/*

NOT WORKING: 
WITH table_list AS (
    SELECT 
    'DB_UOC_PROD.DD_OD.DIM_PERSONA' AS TABLE_NAME
    FROM DB_UOC_PROD.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'DD_OD'
)
SELECT GET_DDL('TABLE', TABLE_NAME) AS create_table_ddl
FROM table_list;

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SELECT *
FROM 
    INFORMATION_SCHEMA.COLUMNS

SELECT GET_DDL('TABLE', TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME) AS create_table_ddl
FROM DB_UOC_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'DD_OD';

*/


-----#################################################################################################


SELECT 'DB_UOC_PROD.DDP_SAA.AEP_AEP_RECONOCIMIENTOS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DDP_SAA.AEP_AEP_RECONOCIMIENTOS') AS ceation  union all
SELECT 'DB_UOC_PROD.DDP_SAA.AEP_AEP_SOLICITUDES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DDP_SAA.AEP_AEP_SOLICITUDES') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_ACCES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_ACCES') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_ASSIGNATURA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_ASSIGNATURA') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_EXPEDIENT' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_EXPEDIENT') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_MATRICULA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_MATRICULA') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_PAIS_NACIM' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PAIS_NACIM') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_PAIS_NACIONALITAT' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PAIS_NACIONALITAT') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_PAIS_RESIDENCIA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PAIS_RESIDENCIA') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_PERSONA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PERSONA') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_PERSONA_ESTUDIANT' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PERSONA_ESTUDIANT') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_PORTAFOLI_PA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_PORTAFOLI_PA') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_QUALIFICACIO' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_QUALIFICACIO') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_QUALIFICACIO_CONTINUADA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_QUALIFICACIO_CONTINUADA') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.DIM_SEMESTRE' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.DIM_SEMESTRE') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.EQUIVALENCIAS_VIASOPCS_UOC_EXTERNAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.EQUIVALENCIAS_VIASOPCS_UOC_EXTERNAS') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.EQUIVALENCIES_PAISOS_CONTINENTS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.EQUIVALENCIES_PAISOS_CONTINENTS') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.FACT_DOCENCIA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.FACT_DOCENCIA') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_ANYS_ACADEMICOS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_ANYS_ACADEMICOS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_ASIG_SEMESTRES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_ASIG_SEMESTRES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DADESRA.GAT_ASIGNATURAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DADESRA.GAT_ASIGNATURAS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_AULAS_ASIG_CONSULTORES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_AULAS_ASIG_CONSULTORES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_CAB_SOLICITUD_ACC' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_CAB_SOLICITUD_ACC') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_CALIF_CONTINUADA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_CALIF_CONTINUADA') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_CALIFICACIONES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_CALIFICACIONES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_CATEGORITZACIONS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_CATEGORITZACIONS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_DESCRIPCIONES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_DESCRIPCIONES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_DISTRIBUIDORS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_DISTRIBUIDORS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_ESTUD_TUTOR_HIST' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_ESTUD_TUTOR_HIST') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_ESTUDIOS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_ESTUDIOS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.GAT_EXP_ASIG_CALIFICACIONES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.GAT_EXP_ASIG_CALIFICACIONES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DADESRA.GAT_EXP_ASIG_MATRICULAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DADESRA.GAT_EXP_ASIG_MATRICULAS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_EXP_MATRICULAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_EXP_MATRICULAS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_EXP_MATRICULAS_CATEGMAT' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_EXP_MATRICULAS_CATEGMAT') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_EXPEDIENTES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_EXPEDIENTES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DADESRA.GAT_PERSONAS_ASIGNATURAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DADESRA.GAT_PERSONAS_ASIGNATURAS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_PLAN_ACCESOS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_PLAN_ACCESOS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_PLAN_DATOS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_PLAN_DATOS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_SOL_ANULA_MAT' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_SOL_ANULA_MAT') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.GAT_VIAS_ACC' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.GAT_VIAS_ACC') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.PROCEDURES_LOG' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.PROCEDURES_LOG') AS ceation  union all
SELECT 'DB_UOC_PROD.MDD_PROGRAM.PROGRAM' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.MDD_PROGRAM.PROGRAM') AS ceation  union all
SELECT 'DB_UOC_PROD.MDD_PROGRAM.PROGRAM_RELACIONES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.MDD_PROGRAM.PROGRAM_RELACIONES') AS ceation  union all
-- SELECT 'DB_UOC_PROD.DD_OD.SEMESTRES_RELATIUS_TEMPORARY_TABLE' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.SEMESTRES_RELATIUS_TEMPORARY_TABLE') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.STAGE_DOCENCIA' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.STAGE_DOCENCIA') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.STAGE_DOCENCIA_POST' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.STAGE_DOCENCIA_POST') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_CODIGOS_POSTALES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_CODIGOS_POSTALES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_UNEIX.TERCERS_COMARCAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_UNEIX.TERCERS_COMARCAS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_COMUNIDADES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_COMUNIDADES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.TERCERS_DATOS_PERSONAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.TERCERS_DATOS_PERSONAS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.TERCERS_DIRECCIONES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.TERCERS_DIRECCIONES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.TERCERS_PAISES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.TERCERS_PAISES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_POBLACIONES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_POBLACIONES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_PROVINCIAS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_DOCENCIA.TERCERS_PROVINCIAS') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_MAT.TERCERS_REF_DIRECCIONES' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.TERCERS_REF_DIRECCIONES') AS ceation  union all
SELECT 'DB_UOC_PROD.STG_UNEIX.TERCERS_TIPO_DOCUMENTOS' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_UNEIX.TERCERS_TIPO_DOCUMENTOS') AS ceation  union all
SELECT 'DB_UOC_PROD.DD_OD.TUTOR_UNIC_PERIODE_HIST' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.DD_OD.TUTOR_UNIC_PERIODE_HIST') AS ceation  --union all
-- SELECT 'DB_UOC_PROD.STG_MAT.TERCERS_PAISOS_NACIONALITAT' AS origen_table , GET_DDL('TABLE', 'DB_UOC_PROD.STG_MAT.TERCERS_PAISOS_NACIONALITAT') AS ceation   























